---
- name: Install AdGuard Home dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Download and install AdGuard Home
  ansible.builtin.shell: |
    curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
  args:
    creates: /opt/AdGuardHome/AdGuardHome

- name: Ensure AdGuard Home is enabled and running
  ansible.builtin.systemd:
    name: AdGuardHome
    state: started
    enabled: yes
