---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: restart immich
  ansible.builtin.systemd:
    name: immich
    state: restarted
    daemon_reload: yes
