---
- name: Add Jellyfin GPG key
  ansible.builtin.shell: |
    curl -fsSL https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | gpg --dearmor -o /usr/share/keyrings/jellyfin.gpg
  args:
    creates: /usr/share/keyrings/jellyfin.gpg

- name: Add Jellyfin APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jellyfin.gpg] https://repo.jellyfin.org/ubuntu jammy main"
    filename: jellyfin
    state: present

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present
    update_cache: yes
  notify: restart jellyfin

- name: Add jellyfin user to media group
  ansible.builtin.user:
    name: jellyfin
    groups: "{{ media_group }}"
    append: yes
  notify: restart jellyfin
